apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-dep
  namespace: osiris
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-app
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: mongo-app
    spec:
      containers:
      - name: mongo
        image: mongo
        imagePullPolicy: IfNotPresent
        ports:
            - containerPort: 27017
