apiVersion: v1
kind: Service
metadata:
  name: mongo-svc
  namespace: osiris
  labels:
    app: mongo-app
spec:
  type: NodePort
  ports:
  - port: 27017
    nodePort: 32000
    protocol: TCP
  selector:
    app: mongo-app
