apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-data
  labels:
    name: mongo-data
  namespace: osiris
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /home/data/mongo